import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salman , Vinayak, Sitadevi , Sagar
 */
public class NewJFrame extends javax.swing.JFrame {

    private String WhoseTurn = "X";
    int X=0,O=0;
    public static int[] a = new int[10];
    public NewJFrame() {
        JOptionPane.showMessageDialog(this,
                 "Welcome to TicTacToe!!!");
        initComponents();
            setSize(450,450);
            setLocationRelativeTo(null);
            
    }
    private void DetermineWhoseTurn(){
        if(WhoseTurn.equalsIgnoreCase("X"))
        {
            WhoseTurn = "O";
            jLabel1.setText("O plays next !!                Score :  X   ="+X+"    O   ="+O);
        }
        else
        {
            WhoseTurn = "X";
            jLabel1.setText("X plays next !!               Score :  X   ="+X+"    O   ="+O);   
        }
    
}
     private void DetermineIfWin()
     {
         String one = jButton1.getText();
         String two = jButton2.getText();
         String three = jButton3.getText();
         String four = jButton4.getText();
         String five = jButton5.getText();
         String six = jButton6.getText();
         String seven = jButton7.getText();
         String eight = jButton8.getText();
         String nine = jButton9.getText();
         if((one == "X" && two == "X" && three == "X") || (one == "X" && four == "X" && seven == "X") || (one == "X" && five == "X" && nine == "X") )
         {
             XWins();
         }
         if((four == "X" && five == "X" && six == "X") || (seven == "X" && eight == "X" && nine == "X") || (two == "X" && five == "X" && eight == "X") )
         {
             XWins();
         }
         if((three == "X" && six == "X" && nine == "X") || (three == "X" && five == "X" && seven == "X"))
         {
             XWins();
         }
                 if((one == "O" && two == "O" && three == "O") || (one == "O" && four == "O" && seven == "O") || (one == "O" && five == "O" && nine == "O") )
         {
             OWins();
         }
         if((four == "O" && five == "O" && six == "O") || (seven == "O" && eight == "O" && nine == "O") || (two == "O" && five == "O" && eight == "O") )
         {
             OWins();
         }
         if((three == "O" && six == "O" && nine == "O") || (three == "O" && five == "O" && seven == "O"))
         {
             OWins();
         }
         if((one =="X" || one == "O") && (two =="X" || two == "O") && (three =="X" || three == "O") && (four =="X" || four == "O") )
         {
          if((five =="X" || five == "O") && (six =="X" || six == "O") && (seven =="X" || seven == "O") && (eight =="X" || eight == "O") && (nine == "X" || nine == "O") )   
          {
               JOptionPane.showMessageDialog(this,
                 "It's a draw");  
               Reset();
              }
         }

     }
     private void XWins()
     {
         X++;
         for(int i=1 ; i<10;i++)
                {
                    a[i]=0;
                }
         if(X==3)
         {
             JOptionPane.showMessageDialog(this,
                 "Player 1 Wins");
             X=0;
             O=0;

         }
         Reset();
     }
          private void OWins()
     {
         O++;
         for(int i=1 ; i<10;i++)
                {
                    a[i]=0;
                }
         if(O==3)
         {
             JOptionPane.showMessageDialog(this,
                 "Player 2 Wins");
         O=0;
         X=0;
         }
          Reset();
     }
    private void Reset()
     {
         WhoseTurn = "X";
         jLabel1.setText("X plays next !!               Score :  X   ="+X+"    O   ="+O);
         for(int i=1 ; i<10;i++)
                {
                    a[i]=0;
                }
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel_2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel_3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel_4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel_5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel_6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel_7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel_8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel_9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X plays next !!                Score :  X   ="+X+"    O   ="+O);
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        jPanel_1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_1.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel_1.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_1);

        jPanel_2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_2.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel_2.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_2);

        jPanel_3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_3.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel_3.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_3);

        jPanel_4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_4.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel_4.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_4);

        jPanel_5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_5.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel_5.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_5);

        jPanel_6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_6.setLayout(new java.awt.BorderLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel_6.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_6);

        jPanel_7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_7.setLayout(new java.awt.BorderLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel_7.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_7);

        jPanel_8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_8.setLayout(new java.awt.BorderLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel_8.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_8);

        jPanel_9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_9.setLayout(new java.awt.BorderLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel_9.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel_9);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
   
    if(a[2]==0)
    {
         jButton2.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[2]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton2.setForeground(Color.blue);   
    DetermineIfWin();
    
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(a[1]==0)
    {
         jButton1.setText(WhoseTurn);
            DetermineWhoseTurn();
         a[1]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton1.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a[3]==0)
    {
         jButton3.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[3]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    
    jButton3.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a[4]==0)
    {
         jButton4.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[4]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton4.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(a[5]==0)
    {
         jButton5.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[5]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton5.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(a[6]==0)
    {
         jButton6.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[6]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton6.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a[7]==0)
    {
         jButton7.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[7]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton7.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a[8]==0)
    {
         jButton8.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[8]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton8.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(a[9]==0)
    {
         jButton9.setText(WhoseTurn);
         DetermineWhoseTurn();
         a[9]++;
    }
    else
        JOptionPane.showMessageDialog(this,"Invalid move");
    jButton9.setForeground(Color.blue);
    DetermineIfWin();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                for(int i=1 ; i<10;i++)
                {
                    a[i]=0;
                }
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_1;
    private javax.swing.JPanel jPanel_2;
    private javax.swing.JPanel jPanel_3;
    private javax.swing.JPanel jPanel_4;
    private javax.swing.JPanel jPanel_5;
    private javax.swing.JPanel jPanel_6;
    private javax.swing.JPanel jPanel_7;
    private javax.swing.JPanel jPanel_8;
    private javax.swing.JPanel jPanel_9;
    // End of variables declaration                   
}
